config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'
  get 'password_resets/edit'
  root "sessions#new"
  get '/signup', to: 'employees#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/portal', to: 'employees#portal'


  get '/adminsignup', to: 'employees#adminsignup'
  get '/alladmins', to: 'employees#alladmins'


  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :admins
  resources :salary
  resources :designations
  resources :employees do
    collection do
      get 'employee_edit'
      get 'employee_portal'
    end

    post "/deactivate", to: "employees#deactivate"
    post "/activate", to: "employees#activate"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  before_action :get_employee,   only: [:edit, :update]
  before_action :valid_employee, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  def new
  end
def create
  @employee = Employee.find_by(email: params[:password_reset][:email].downcase)
  if @employee
    @employee.create_reset_digest
    @employee.send_password_reset_email
    flash[:info] = "Email sent with password reset instructions"
redirect_to root_url

  else
    flash[:danger] = "Email address not found"
    render 'new'

  end
end

  def update
    if params[:employee][:password].empty?                  # Case (3)
      @employee.errors.add(:password, "can't be empty")
      render 'edit'
    elsif @employee.update_attributes(employee_params)          # Case (4)
      flash[:success] = "Password has been reset."
      redirect_to root_url
    else
      render 'edit'                                     # Case (2)
    end
  end

  def edit
  end

  private
  def employee_params
    params.require(:employee).permit(:password, :password_confirmation)
  end

  def get_employee
    @employee = Employee.find_by(email: params[:email])
  end

  # Checks expiration of reset token.
  def check_expiration
    if @employee.password_reset_expired?
      flash[:danger] = "Password reset has expired."
      redirect_to new_password_reset_url
    end
  end

  # Confirms a valid user.
  def valid_employee
    unless (@employee &&
        @employee.authenticated?(:reset, params[:id]))
      redirect_to root_url
    end
  end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<!----------------------------------------------------------------->

<body class="bg-gradient-primary">

<div class="container">

  <!-- Outer Row -->
  <div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                  <p class="mb-4"> Enter your password below and we'll reset your password!</p>
                </div>
                <%= form_for(@employee, url: password_reset_path(params[:id])) do |f| %>
                    <%= render 'shared/error_messages', object: f.object %>

                    <%= hidden_field_tag :email, @employee.email %>

                    <%= f.label :password %>
                    <%= f.password_field :password, class: 'form-control', placeholder: "Password" %>

                    <%= f.label :password_confirmation, "Confirmation" %>
                    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Confirm Password"%>
<br>
                    <%= f.submit "Update password", class: "btn btn-primary btn-user btn-block" %>
                <% end %>

                <!--  <form class="user">
                    <div class="form-group">
                      <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                    </div>
                    <a href="login.html" class="btn btn-primary btn-user btn-block">
                      Reset Password
                    </a>
                  </form>-->
                <hr>

                <div class="text-center">
                  <a class="small" href="<%= login_path %>">Don't want reset? Login!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>



</body>

app/views/password_resets/new.html.erb
<body class="bg-gradient-primary">

<div class="container">

  <!-- Outer Row -->
  <div class="row justify-content-center">

    <div class="col-xl-10 col-lg-12 col-md-9">

      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
            <div class="col-lg-6">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                  <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
                </div>

                <%= form_for(:password_reset, url: password_resets_path) do |f| %>
                    <div class="form-group">
                      <%= f.email_field :email, class: 'form-control form-control-user', id:"exampleInputEmail", placeholder:"Enter Email Address..." %>
                    </div>

                    <%= f.submit "Submit", class: "btn btn-primary btn-user btn-block" %>
                <% end %>
              <!--  <form class="user">
                  <div class="form-group">
                    <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                  </div>
                  <a href="login.html" class="btn btn-primary btn-user btn-block">
                    Reset Password
                  </a>
                </form>-->
                <hr>

                <div class="text-center">
                  <a class="small" href="<%= login_path %>">Already have an account? Login!</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>



</body>