config/routes.rb
Rails.application.routes.draw do


  get 'password_resets/new'
  get 'password_resets/edit'
  root "sessions#new"
  get '/signup', to: 'employees#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/portal', to: 'employees#portal'


  get '/adminsignup', to: 'employees#adminsignup'
  get '/alladmins', to: 'employees#alladmins'


  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :admins
  resources :salary
  resources :designations
  resources :employees do
    collection do
      get 'employee_edit'
      get 'employee_portal'
    end

    post "/deactivate", to: "employees#deactivate"
    post "/activate", to: "employees#activate"
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :salaries, dependent: :destroy
  has_many :processed_salaries, class_name: "Salary", foreign_key: "admin_id"
  has_many :documents, as: :documentable
  accepts_nested_attributes_for :documents, reject_if: :all_blank


  belongs_to :designation



  scope :admins, -> { where(admin: true) }
  scope :employees, -> { where(admin: false) }


  attr_accessor :reset_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :joining_date, presence: true
  validates :gross_salary, numericality: {only_integer: true}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  def image_path

    self.documents.profile_pic.first

  end



  def activate_account!
    update_attribute :status, true
  end

  def deactivate_account!
    update_attribute :status, false
  end

  # Returns the hash digest of the given string.
  def Employee.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def Employee.new_token
    SecureRandom.urlsafe_base64
  end


  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Sets the password reset attributes.
  def create_reset_digest
    self.reset_token = Employee.new_token
    update_attribute(:reset_digest, Employee.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    EmployeeMailer.password_reset(self).deliver_now
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :check_login?
  def portal
    @salaries = current_user.salaries
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def new
    @employee = Employee.new
    @designation = Designation.all
    @document = @employee.documents.profile_pic.first.present? ? @employee.documents.profile_pic.first : @employee.documents.profile_pic.build
  end

  def adminsignup
    @employee = Employee.new(admin: true)

  end

  def edit
    @employee = Employee.find(params[:id])
    @designation = Designation.all
  end

  def employee_edit
    @employee = current_user
    @designation = Designation.all
  end

  def create

    @employee = Employee.new(employee_params)

    if @employee.save
      if @employee.admin==true
        redirect_to alladmins_path
      else
        redirect_to employees_path
      end

    else
      render 'new'
    end
  end

  def index
    @employees = Employee.paginate(page: params[:page])
  end

  def alladmins
    @employees = Employee.paginate(page: params[:page])
  end

  def deactivate
    @employee = Employee.find(params[:employee_id])
    if current_user.admin?
      @employee.deactivate_account!
      flash[:success] = "Deactivated"
      redirect_to employees_path
    else
      redirect_to :back
    end
  end


  def activate
    @employee = Employee.find(params[:employee_id])
    if current_user.admin?
      @employee.activate_account!
      flash[:success] = "Activated"
      redirect_to employees_path
    else
      redirect_to :back
    end
  end


  def update
    @employee = Employee.find(params[:id])
    @designation = Designation.all
    @document = @employee.documents.profile_pic.first.present? ? @employee.documents.profile_pic.first : @employee.documents.profile_pic.build
    if current_user.admin
      if @employee.update(employee_params)
        update_image
        flash[:success] = "Profile updated"
        redirect_to employees_path
      else
        render 'edit'
      end
    else
      if @employee.update(employee_params)
        update_image
        flash[:success] = "Profile updated"
        redirect_to employee_path
      else
        render 'employee_edit'
      end
    end
    # @employee.documents.find(params[:employee][:documents_attributes]["0"][:id]).update(avatar: params[:employee][:documents_attributes]["0"][:avatar])
  end

  def update_image
    if(@document.persisted?)
      @document.update(avatar: params[:employee][:avatar])
    else
      @document.avatar = params[:employee][:avatar]
      @document.save
    end
  end


  def destroy
    Employee.find(params[:id]).destroy
    flash[:success] = "Employee deleted"
    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :email, :password, :password_confirmation, :joining_date, :status, :admin, :gross_salary, :designation_id,
                                     documents_attributes: [:id, :documentable_type, :documentable_id,
                                                            :document_type, :avatar])



  end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/adminsignup.html.erb
<% provide(:title, ' Admin Sign up') %>

<!------------------------------------->

<body class="bg-gradient-primary">

<div class="container">

  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-admin"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              <h1 class="h4 text-gray-900 mb-4">Admin Sign Up!</h1>
            </div>

            <%= form_for(@employee) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>

                <div class="form-group">
                  <%= f.text_field :name, class: 'form-control form-control-user', id: "exampleFirstName", placeholder: "Name" %>
                </div>

                <div class="form-group">
                  <%= f.email_field :email, class:"form-control form-control-user" ,id:"exampleInputEmail", placeholder:"Email Address" %>
                </div>

                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <%= f.password_field :password, class:"form-control form-control-user", id:"exampleInputPassword", placeholder:"Password" %>
                  </div>
                  <div class="col-sm-6">
                    <%= f.password_field :password_confirmation,class:"form-control form-control-user", id:"exampleRepeatPassword", placeholder:"Confirm Password" %>
                  </div>
                </div>
                <div class="form-group">
                  <%= f.date_field :joining_date, class: 'form-control form-control-user', id: "exampleJoiningDate", placeholder: "Joining Date" %>
                </div>

                <div class="form-group">
                  <%= f.text_field :gross_salary, class: 'form-control form-control-user', id: "exampleGrossSalary", placeholder: "Salary" %>
                </div>

                <%= f.hidden_field :admin, value: true %>

                <%= f.submit "Add Admin", class: "btn btn-primary btn-user btn-block" %>
            <% end %>
            <!--  <form class="user">
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name">
                  </div>
                </div>
                <div class="form-group">
                  <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address">
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                  </div>
                  <div class="col-sm-6">
                    <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repeat Password">
                  </div>
                </div>
                <a href="login.html" class="btn btn-primary btn-user btn-block">
                  Register Account
                </a>
                <hr>
                <a href="index.html" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Register with Google
                </a>
                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                  <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                </a>
              </form> -->
            <hr>

            <div class="text-center">
              <a class="small" href="<%= portal_path %>">Don't want to create Account? Back!</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>


</body>

app/views/employees/alladmins.html.erb
<% provide(:title, 'All Admins') %>
<h1>All Admins</h1>

<%= will_paginate %>
<div class="container employees">

  <ul>
    <% @employees.admins.each do |employee| %>
        <li>


              <%= link_to employee.name.humanize, employee %>



              <% if employee.status == true %>

                  <button class=" btn-lg btn-dark float-right" style=" margin-right:20px;"    > <%= link_to "Deactivate",  employee_deactivate_path(employee), method: :post, data: { confirm: "Are you sure?" } %> </button>

              <%else%>
                  <button class="btn-lg btn-success float-right" style=" margin-right:20px; width:13%" >  <%= link_to "Activate",  employee_activate_path(employee), method: :post, class: "temp2", data: { confirm: "Are you sure?" } %>
                  </button>
              <%end %>

              <button class="btn-lg btn-danger float-right" style=" margin-right:20px; width:13%" >  <%= link_to "Delete", employee, method: :delete,
                                                                                                                 data: { confirm: "You sure?" } %> </button>
              <button class="btn-lg btn-info float-right" style=" margin-right:20px; width:13%" >  <%= link_to "Update", edit_employee_path(employee) %>
              </button>



        </li>
    <% end %>
  </ul>

</div>

<br>
<button class="btn btn-primary btn-user btn-block" > <%= link_to "Back", portal_path, class: "temp"  %>  </button>


<%= will_paginate %>

app/views/employees/edit.html.erb
<% provide(:title, 'Update') %>

<!------------------------------------->

<body class="bg-gradient-primary">

<div class="container">

  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-update"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              <h1 class="h4 text-gray-900 mb-4">Update employee!</h1>
            </div>

            <%= form_for(@employee) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>

                    <%= f.file_field :avatar %>

                <br>
                <div class="form-group">
                  <%= f.text_field :name, class: 'form-control form-control-user', id: "exampleFirstName", placeholder: "Name" %>
                </div>

                <div class="form-group">
                  <%= f.email_field :email, class: "form-control form-control-user", id: "exampleInputEmail", placeholder: "Email Address" %>
                </div>

                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <%= f.password_field :password, class: "form-control form-control-user", id: "exampleInputPassword", placeholder: "Password" %>
                  </div>
                  <div class="col-sm-6">
                    <%= f.password_field :password_confirmation, class: "form-control form-control-user", id: "exampleRepeatPassword", placeholder: "Confirm Password" %>
                  </div>
                </div>
                <div class="form-group">
                  <%= f.date_field :joining_date, class: 'form-control form-control-user', id: "exampleJoiningDate", placeholder: "Joining Date" %>
                </div>

                <%= f.select :designation_id, @designation.collect { |p| [p.name.humanize, p.id] }, {include_blank: "Select something"}, {:class => "dropdown"} %>

                <%= f.submit "Save Changes", class: "btn btn-primary btn-user btn-block" %>
            <% end %>
            <!--  <form class="user">
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name">
                  </div>
                </div>
                <div class="form-group">
                  <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address">
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                  </div>
                  <div class="col-sm-6">
                    <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repeat Password">
                  </div>
                </div>
                <a href="login.html" class="btn btn-primary btn-user btn-block">
                  Register Account
                </a>
                <hr>
                <a href="index.html" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Register with Google
                </a>
                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                  <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                </a>
              </form> -->
            <hr>

            <div class="text-center">
              <a class="small" href="<%= portal_path %>">Don't want to update Account? Back!</a>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>


</body>

app/views/employees/employee_edit.html.erb
<% provide(:title, 'Update') %>

<!------------------------------------->

<body class="bg-gradient-primary">

<div class="container">

  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-update"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              <h1 class="h4 text-gray-900 mb-4">Update Profile!</h1>
            </div>

            <%= form_for(@employee) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>

                <%= f.file_field :avatar %>
<br>
                <div class="form-group">
                  <%= f.text_field :name, class: 'form-control form-control-user', id: "exampleFirstName", placeholder: "Name" %>
                </div>

                <div class="form-group">
                  <%= f.email_field :email, class: "form-control form-control-user", id: "exampleInputEmail", placeholder: "Email Address" %>
                </div>

                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <%= f.password_field :password, class: "form-control form-control-user", id: "exampleInputPassword", placeholder: "Password" %>
                  </div>
                  <div class="col-sm-6">
                    <%= f.password_field :password_confirmation, class: "form-control form-control-user", id: "exampleRepeatPassword", placeholder: "Confirm Password" %>
                  </div>
                </div>
                <div>

                  <%= f.select :designation_id, @designation.collect { |p| [p.name.humanize, p.id] }, {include_blank: "Select something"}, {:class => "dropdown"} %>

                </div>


                <%= f.submit "Save Changes", class: "btn btn-primary btn-user btn-block" %>
            <% end %>
            <!--  <form class="user">
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name">
                  </div>
                </div>
                <div class="form-group">
                  <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address">
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                  </div>
                  <div class="col-sm-6">
                    <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repeat Password">
                  </div>
                </div>
                <a href="login.html" class="btn btn-primary btn-user btn-block">
                  Register Account
                </a>
                <hr>
                <a href="index.html" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Register with Google
                </a>
                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                  <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                </a>
              </form> -->
            <hr>

            <div class="text-center">
              <a class="small" href="<%= employee_path(current_user) %>">Don't want to update Account? Back!</a>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>

</div>


</body>

app/views/employees/index.html.erb
<% provide(:title, 'All Employees') %>
<h1>All Employees</h1>

<%= will_paginate %>
<div class="container employees">

  <ul>
    <% @employees.employees.each do |employee| %>
        <li>


              <%= link_to employee.name.humanize, '#' %>



  <% if employee.status == true %>

      <button class=" btn-lg btn-dark float-right" style=" margin-right:20px;"    > <%= link_to "Deactivate",  employee_deactivate_path(employee), method: :post, data: { confirm: "Are you sure?" } %> </button>

  <%else%>
      <button class="btn-lg btn-success float-right" style=" margin-right:20px; width:13%" >  <%= link_to "Activate",  employee_activate_path(employee), method: :post, class: "temp2", data: { confirm: "Are you sure?" } %>
      </button>
  <%end %>

  <button class="btn-lg btn-danger float-right" style=" margin-right:20px; width:13%" >  <%= link_to "Delete", employee, method: :delete,
                                                                                         data: { confirm: "You sure?" } %> </button>
  <button class="btn-lg btn-info float-right" style=" margin-right:20px; width:13%" >  <%= link_to "Update", edit_employee_path(employee) %>
  </button>



        </li>
    <% end %>
  </ul>

</div>

<br>
<button class="btn btn-primary btn-user btn-block" > <%= link_to "Back", portal_path, class: "temp"  %>  </button>


<%= will_paginate %>

app/views/employees/new.html.erb
<% provide(:title, 'Sign up') %>

<!------------------------------------->

<body class="bg-gradient-primary">

<div class="container">

  <div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
      <!-- Nested Row within Card Body -->
      <div class="row">
        <div class="col-lg-5 d-none d-lg-block bg-register"></div>
        <div class="col-lg-7">
          <div class="p-5">
            <div class="text-center">
              <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
            </div>

            <%= form_for(@employee) do |f| %>
                <%= render 'shared/error_messages', object: f.object %>

                <%= f.fields_for :documents , @document  do |d| %>
                    <%= d.file_field :avatar %>
                    <%= d.hidden_field :document_type, value: "profile_pic" %>
                <% end %>
                <br>

                <div class="form-group">
                  <%= f.text_field :name, class: 'form-control form-control-user', id: "exampleFirstName", placeholder: "Name" %>
                </div>

                <div class="form-group">
                  <%= f.email_field :email, class: "form-control form-control-user", id: "exampleInputEmail", placeholder: "Email Address" %>
                </div>

                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <%= f.password_field :password, class: "form-control form-control-user", id: "exampleInputPassword", placeholder: "Password" %>
                  </div>
                  <div class="col-sm-6">
                    <%= f.password_field :password_confirmation, class: "form-control form-control-user", id: "exampleRepeatPassword", placeholder: "Confirm Password" %>
                  </div>
                </div>
                <div class="form-group">
                  <%= f.date_field :joining_date, class: 'form-control form-control-user', id: "exampleJoiningDate", placeholder: "Joining Date" %>
                </div>

                <div class="form-group">
                  <%= f.number_field :gross_salary, class: 'form-control form-control-user', id: "exampleGrossSalary", placeholder: "Salary" %>
                </div>

                <div>

                  <%= f.select :designation_id, @designation.collect { |p| [p.name.humanize, p.id] }, {include_blank: "Select something"}, {:class => "dropdown"} %>

                </div>

                <%= f.submit "Create employee account", class: "btn btn-primary btn-user btn-block" %>
            <% end %>
            <!--  <form class="user">
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" id="exampleFirstName" placeholder="First Name">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user" id="exampleLastName" placeholder="Last Name">
                  </div>
                </div>
                <div class="form-group">
                  <input type="email" class="form-control form-control-user" id="exampleInputEmail" placeholder="Email Address">
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Password">
                  </div>
                  <div class="col-sm-6">
                    <input type="password" class="form-control form-control-user" id="exampleRepeatPassword" placeholder="Repeat Password">
                  </div>
                </div>
                <a href="login.html" class="btn btn-primary btn-user btn-block">
                  Register Account
                </a>
                <hr>
                <a href="index.html" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Register with Google
                </a>
                <a href="index.html" class="btn btn-facebook btn-user btn-block">
                  <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                </a>
              </form> -->
            <hr>

            <div class="text-center">
              <a class="small" href="<%= portal_path %>">Don't want to create Account? Back!</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>


</body>

app/views/employees/show.html.erb
<head>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


</head>
<!------ Include the above in your HEAD tag ---------->
<body>


<div class="container emp-profile">
  <form method="post">
    <div class="row">
      <div class="col-md-4">
        <div class="profile-img">

          <%= image_tag current_user.image_path&.avatar&.attached? ? url_for(current_user.image_path.avatar) : "admin.png" %>

          <div class="file btn btn-lg btn-primary">
            Change Photo
            <input type="file" name="file"/>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="profile-head">
          <h5>
            <%= current_user.name.humanize %>
          </h5>
          <h6>
            <%= current_user.designation.name %>
          </h6>
          <p class="proile-rating">RANKINGS : <span>8/10</span></p>
          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-2">

        <button type="submit" class="profile-edit-btn"> <%= link_to "Edit Profile", employee_edit_employees_path %> </button>

      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <div class="profile-work">
          <p>WORK LINK</p>
          <a href="">Website Link</a><br/>
          <a href="">Bootsnipp Profile</a><br/>
          <a href="">Bootply Profile</a>
          <p>SKILLS</p>
          <a href="">Web Designer</a><br/>
          <a href="">Web Developer</a><br/>
          <a href="">WordPress</a><br/>
          <a href="">WooCommerce</a><br/>
          <a href="">PHP, .Net</a><br/>
        </div>
      </div>
      <div class="col-md-8">
        <div class="tab-content profile-tab" id="myTabContent">
          <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            <div class="row">
              <div class="col-md-6">
                <label>User Id</label>
              </div>
              <div class="col-md-6">
                <p> <%= current_user.id %></p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <label>Name</label>
              </div>
              <div class="col-md-6">
                <p><%= current_user.name.humanize %></p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <label>Email</label>
              </div>
              <div class="col-md-6">
                <p><%= current_user.email %></p>
              </div>
            </div>

            <div class="row">
              <div class="col-md-6">
                <label>Profession</label>
              </div>
              <div class="col-md-6">
                <p><%= current_user.designation.name.humanize %></p>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <div class="row">
              <div class="col-md-6">
                <label>Experience</label>
              </div>
              <div class="col-md-6">
                <p>Expert</p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <label>Hourly Rate</label>
              </div>
              <div class="col-md-6">
                <p>10$/hr</p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <label>Total Projects</label>
              </div>
              <div class="col-md-6">
                <p>230</p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <label>English Level</label>
              </div>
              <div class="col-md-6">
                <p>Expert</p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-6">
                <label>Availability</label>
              </div>
              <div class="col-md-6">
                <p>6 months</p>
              </div>
            </div>
            <div class="row">
              <div class="col-md-12">
                <label>Your Bio</label><br/>
                <p>Your detail description</p>
              </div>
            </div>
          </div>
        </div>

      </div>
      <button class="btn btn-primary btn-block" style="margin-left:40px;" > <%= link_to "Back", portal_path(current_user), class: "temp" %>  </button>

    </div>
  </form>

</div>


</body>